[general]
import = []

[colors.primary]
background = "#181818"
foreground = "#E4E4E4"

[colors.normal]
black = "#181818"

red = "#F43841"
green = "#73D936"
yellow = "#FFDD33"
blue = "#96A6C8"
magenta = "#9E95C7"
cyan = "#95A99F"
white = "#E4E4E4"

[colors.bright]
black = "#52494E"
red = "#FF4F58"
green = "#73D936"
yellow = "#FFDD33"
blue = "#96A6C8"
magenta = "#AFAFD7"
cyan = "#95A99F"
white = "#F5F5F5"

[env]
TERM = "xterm-256color"

[font]
normal = { family = "ComicShannsMono Nerd Font", style = "Regular" }
bold = { family = "ComicShannsMono Nerd Font", style = "Bold" }
italic = { family = "ComicShannsMono Nerd Font", style = "Italic" }
size = 9

[window]
padding = { x = 14, y = 14 }
decorations = "none"

[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"
