add_newline = false

# format = """
# [==> ](red)$directory$git_branch$character
# """
format = """
$directory$git_branch$git_status
; 
"""

[directory]
style = "#008080"

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
staged = '[++\($count\)](green)'
