add_newline = false

format = "$git_status$custom$directory"

[custom.todo]
command = "awk '/^TODAY/{getline; if (NF) {print; exit}}' ~/do"
when = "grep -A1 '^TODAY' ~/do | tail -n1 | grep -q '.'"
style = "bold white"
format = "\"[$output]($style)\" "
